#exception handling
try:
    print("give")
except:
    print(x)
print("give")
print("give")
print("give")